### ISSUE TITLE
Compilation Error Execution failed for task

### ISSUE THREAD

**Issue by JRTStudio** [MichaelRocks/paranoid#49]
I'm unable to compile with version 0.3.3. I get the following error message.

Execution failed for task ':Tools:transformClassesWithParanoidForMyProjectDebug'.
> 'void kotlin.jvm.internal.MutablePropertyReference1Impl.<init>(java.lang.Class, java.lang.String, java.lang.String, int)'

On subsequent compiles I get the following variation.
Execution failed for task ':Tools:transformClassesWithParanoidForMyProjectDebug'.
> Could not initialize class io.michaelrocks.paranoid.grip.ClassesQueryBuilder

I have added Kotlin to my project and used the same version as paranoid (1.4.31). I don't know what else I need to do/configure.

**Comment by MichaelRocks** [comment]
Could you check please if the version 0.3.2 works?

**Comment by JRTStudio** [comment]
It does.

**Comment by MichaelRocks** [comment]
What version of Kotlin and Gradle do you use?

**Comment by bassil-altamimi** [comment]
I'm not using Kotlin, it's a completely Android - Java project, V0.3.2 was working fine and I downgraded my project.

**Comment by MichaelRocks** [comment]
@bassil-altamimi And what's the Gradle version? Could you please try and build the project with Gradle 6.8 or 7.0?

**Comment by bassil-altamimi** [comment]
@MichaelRocks I was using Gradle 6.5, I just upgraded to Gradle 6.8 and it works as expected with V0.3.3

**Comment by MichaelRocks** [comment]
So the issue is that Gradle 6.5 uses Kotlin 1.3 and the Paranoid plugin is compiled with Kotlin 1.4. Unfortunately, these two Kotlin versions seem to be [binary incompatible](https://youtrack.jetbrains.com/issue/KT-37435). Therefore, you can either upgrade Gradle to 6.8 or later, or downgrade Paranoid to 0.3.2.

**Comment by bassil-altamimi** [comment]
correct
